<?php
/*
 * ContentToolsLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace ContentToolsLib;

/**
 * All configuration including auth info and base URI for the API access
 * are configured in this class.
 */
class Configuration
{
    /**
     * The base Uri for API calls
     * @var string
     */
    public static $BASEURI = 'https://contenttools.club/api';

    /**
     * OAuth 2.0 Access Token
     * @var string
     */
    public static $oAuthAccessToken = 'TODO: Replace';
}
